config/routes.rb
Rails.application.routes.draw do
  resources :contrats
  resources :information
  devise_for :users

  get 'contrats/:id/remplacement', to: 'contrats#remplacement', as: 'remplacement_contrat'
  get 'contrats/:id/assistanat', to: 'contrats#assistanat', as: 'assistanat_contrat'
  get 'contrats/:id/collaboration', to: 'contrats#collaboration', as: 'collaboration_contrat'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'publics#home'
end

app/models/information.rb
class Information < ApplicationRecord
    belongs_to :user
    has_many :contrats
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: %i[ show edit update destroy ]
  before_action :require_login
  before_action :require_permission, only: %i[ show edit update destroy ]

  # GET /information or /information.json
  def index
    @information = current_user.information
  end

  # GET /information/1 or /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = current_user.build_information
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information or /information.json
  def create
    @information = current_user.information.build(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to information_url(@information), notice: "Fiche Information crée" }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1 or /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to information_url(@information), notice: "Information was successfully updated." }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1 or /information/1.json
  def destroy
    @information.destroy

    respond_to do |format|
      format.html { redirect_to information_index_url, notice: "Information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    def require_login
      unless current_user
        flash[:error] = "Vous devez être connecté pour accéder à cette section."
        redirect_to new_user_session_path # rediriger vers la page de connexion
      end
    end

    def require_permission
      unless current_user.information.id == @information.id
        flash[:error] = "Vous n'êtes pas autorisé à effectuer cette action."
        redirect_to information_path # rediriger vers la page d'information
      end
    end
    
    # Only allow a list of trusted parameters through.
    def information_params
      params.require(:information).permit(:name, :first_name, :birthday, :place_birth, :gender, :diploma, :graduation_date, :place_diploma, :n_ordinal, :registered_ordre, :address_pro, :name_street, :street_number, :address_complement, :zip_code, :city, :country, :usage_name, :nationality, :n_secu, :rpps)
    end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_with(model: information) do |form| %>
    <% if information.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

        <ul>
          <% information.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
  <div class="center">
    <div class="column">
      <div >
        <%= form.label :gender, "Genre :", style: "display: block" %>
        <%= form.select :gender, ['Monsieur', 'Madame'] %>
      </div>
      
      <div>
        <%= form.label :usage_name, "Nom d'usage:", style: "display: block" %>
        <%= form.text_field :usage_name %>
      </div>

      <div>
        <%= form.label :nationality, "Nationalité :", style: "display: block" %>
        <%= form.text_field :nationality %>
      </div>

      <div>
        <%= form.label :place_birth, "Lieu de naissance :", style: "display: block" %>
        <%= form.text_field :place_birth %>
      </div>

      <div>
        <%= form.label :graduation_date, "Date d'obtention :", style: "display: block" %>
        <%= form.date_field :graduation_date %>
      </div>

      <div>
        <%= form.label :n_ordinal, "Numéro ordinal :", style: "display: block" %>
        <%= form.number_field :n_ordinal, prompt: 'xx xxxxxxx' %>
      </div>

      <div>
        <%= form.label :street_number, "Numéro de la rue :", style: "display: block" %>
        <%= form.number_field :street_number %>
        <%= form.label :address_complement, "Complément :", style: "display: block" %>
        <%= form.text_field :address_complement %>
        <%= form.label :city, "Ville :", style: "display: block" %>
        <%= form.text_field :city %>
      </div>

      <div>
        <%= form.label :n_secu, "Numéro de sécurité sociale :", style: "display: block" %>
        <%= form.number_field :n_secu, prompt: 'x xx xx xx xxx xxx xx' %>
      </div>

      <div>
        <%= form.label :rpps, "Numéro rpps :", style: "display: block" %>
        <%= form.number_field :rpps, prompt: 'x xxxxxxxx xx', class: 'field_box' %>
      </div>
    </div>
        
    <div class="column">
      <div >
        <%= form.label :name, "Nom :", style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :first_name, "Prénom :", style: "display: block" %>
        <%= form.text_field :first_name %>
      </div>

      <div>
        <%= form.label :birthday, "Date de naissance :", style: "display: block" %>
        <%= form.date_select :birthday, { prompt: true, start_year: Date.today.year - 80, end_year: Date.today.year - 18 } %>
      </div>

      <div>
        <%= form.label :diploma, "Intitulé du diplôme :", style: "display: block" %>
        <%= form.text_field :diploma %>
      </div>

      <div>
        <%= form.label :place_diploma, "Lieu d'obtention :", style: "display: block" %>
        <%= form.text_field :place_diploma %>
      </div>

      <div>
        <%= form.label :registered_ordre, "Inscrit à l'Ordre de :", style: "display: block" %>
        <%= departement_select(form, :registered_ordre) do %>
          <% if form.object.registered_ordre.present? %>
            <%= content_tag(:option, form.object.registered_ordre, value: form.object.registered_ordre, selected: true) %>
          <% end %>
        <% end %>
      </div>

      <div>
        <%= form.label :name_street, "Nom de la rue :", style: "display: block" %>
        <%= form.text_field :name_street %>
        <%= form.label :zip_code, "Code postal :", style: "display: block" %>
        <%= form.number_field :zip_code %>
        <%= form.label :country, "Pays :", style: "display: block" %>
        <%= form.text_field :country %>
      </div>

      <div>
        <%= form.label :address_pro, "Adresse professionel :", style: "display: block" %>
        <%= form.text_field :address_pro %>
      </div>
    </div>
  </div>

  <div class="center">
    <%= form.submit "Enregistrer", class: 'btn btn--primary' %>
  </div>
<% end %>

app/views/information/_information.html.erb
<div id="<%= dom_id information %>">
  <div class="center">
    <div class="column">
      <p>
        <strong><%= "#{information.gender} #{information.name}" %></strong>
      </p>

      <p>
        <strong>Née le :</strong>
        <%= information.birthday.strftime('%d/%m/%Y') %>
      </p>

      <p>
        <strong>Profession :</strong>
        <%= information.diploma %>
      </p>

      <p>
        <strong>Lieu :</strong>
        <%= information.place_diploma %>
      </p>

      <p>
        <strong>Inscrit à l'ordre :</strong>
        <%= information.registered_ordre %>
      </p>
    </div>

    <div class="column">
      <p>
        <strong> <%= information.first_name %> </strong>
      </p>

      <p>
        <strong>À :</strong>
        <%= information.place_birth %>
      </p>

      <p>
        <strong>Diplômé le :</strong>
        <%= information.graduation_date.strftime('%d/%m/%Y') %>
      </p>

      <p>
        <strong>Numéro ordinal :</strong>
        <%= information.n_ordinal %>
      </p>

      <p>
        <strong>Adresse pro :</strong>
        <%= information.address_pro %>
      </p>
  </div>
</div>

app/views/information/edit.html.erb
<div class="header">
  <h1>Modifier mes informations</h1>
</div>

<div class="container">
  <div class="form">
    <%= render "form", information: @information %>
  </div>
</div>

app/views/information/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="header">
  <h1>Mes informations</h1>
</div>

<div id="information" class="container">
    <div class="form">
        <div class="center center--line">
            <p>
                <strong>Email :</strong>
                <%= current_user.email %>
            </p>
            <p>
                <strong>Mot de passe :</strong>
                <%= "********" %>
            </p>
            <%= link_to "Modifier", edit_user_registration_path(@current_user), class: 'btn btn--light' %>
        </div>
    </div>

    <div class="form">
        <% if current_user.information %>
            <%= render @information %>
            <div class="option option--center">
                <%= link_to "Modifier", edit_information_path(@information), class: 'btn btn--primary' %>
            </div>
        <% else %>
            <p>Aucune fiche d'information créée.</p>
            <div class="option option--center">
                <%= link_to "Créer", new_information_path(@information), class: 'btn btn--primary' %>
            </div>
        <% end %>
    </div>
</div>
</div>

app/views/information/new.html.erb
<div class="header">
  <h1>Ma fiche information</h1>
</div>

<div class="container">
  <div class="form">
    <%= render "form", information: @information %>
  </div>
</div>

app/views/information/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="form">
    <%= render @information %>

    <div class="option">
      <%= link_to "Modifier", edit_information_path(@information), class: 'btn btn--light' %>
      <%= link_to "retour", information_index_path, class: 'btn btn--light' %>
      <%= button_to "Supprimer", @information, method: :delete, class: 'btn btn--light' %>
    </div>
  </div>
</div>