config/routes.rb
Rails.application.routes.draw do
  resources :contrats
  resources :information
  devise_for :users

  get 'contrats/:id/remplacement', to: 'contrats#remplacement', as: 'remplacement_contrat'
  get 'contrats/:id/assistanat', to: 'contrats#assistanat', as: 'assistanat_contrat'
  get 'contrats/:id/collaboration', to: 'contrats#collaboration', as: 'collaboration_contrat'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'publics#home'
end

app/models/contrat.rb
class Contrat < ApplicationRecord
  belongs_to :information
  belongs_to :user

  enum name_contrat: {
    remplacement: "Remplacement",
    collaboration: "Collaborateur",
    assistanat: "Assistanat"
  }

  validates :name_contrat, presence: true
  validates :gender, presence: true
  validates :name, presence: true
  validates :first_name, presence: true
  validates :birthday, presence: true
  validates :place_birth, presence: true
  validates :registered_ordre, presence: true
  validates :n_ordinal, presence: true
  validates :address_pro, presence: true
  validates :email, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :retro, presence: true
  validates :payment_limit, presence: true
  validates :rayon_install, presence: true
  validates :conflict_order, presence: true
  validates :made_on, presence: true
  validates :to, presence: true
  validates :status, presence: true
  validates :nb_refus, presence: true, if: -> { name_contrat.in?(["collaboration", "assistanat"]) }
  validates :n_urssaf, presence: true, if: -> { name_contrat.in?(["collaboration", "assistanat"]) }
  validates :blackout_period, presence: true, if: -> { name_contrat.in?(["collaboration", "assistanat"]) }

end

app/controllers/contrats_controller.rb
class ContratsController < ApplicationController
  before_action :set_contrat, only: %i[ show edit update destroy remplacement assistanat collaboration statu ]
  before_action :authenticate_user!
  before_action :set_status, only: [ :remplacement, :show, :assistanat, :collaboration ]
  # GET /contrats or /contrats.json
  def index
    @contrats = current_user.contrats.limit(5)
  end

  # GET /contrats/1 or /contrats/1.json
  def show
    respond_to do |format|
      format.html
    end
  end
  
  # GET /contrats/new
  def new
    @contrat = current_user.contrats.build(contrat_params)
  end

  # GET /contrats/1/edit
  def edit
  end

  # POST /contrats or /contrats.json
  def create
    # Créer un nouveau contrat
    information = current_user.information
    @contrat = information.contrats.build(contrat_params)
    @contrat.user_id = current_user.id
    respond_to do |format|
      if @contrat.save
        format.html { redirect_to contrat_url(@contrat), notice: "Contrat créé avec succès." }
        format.json { render :show, status: :created, location: @contrat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contrat.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /contrats/1 or /contrats/1.json
  def update
    respond_to do |format|
      if @contrat.update(contrat_params)
        format.html { redirect_to contrat_url(@contrat), notice: "Contrat mis à jour avec succès." }
        format.json { render :show, status: :ok, location: @contrat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contrat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contrats/1 or /contrats/1.json
  def destroy
    @contrat.destroy

    respond_to do |format|
      format.html { redirect_to contrats_url, notice: "Contrat supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  def remplacement
    data = {
      "Madame" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "ou Monsieur" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "Née le" => @first_person.birthday.strftime('%d/%m/%Y'),
      "à" => @first_person.place_birth,
      "Inscrit e au tableau du Conseil départemental de lordre de" => @first_person.registered_ordre,
      "sous le numéro" => @first_person.n_ordinal,
      "Adresse professionnelle" => @first_person.address_pro,
      "Adresse électronique" => @contrat.status == "perso_1" ? current_user.email : @contrat.email,
      "Madame_2" => @second_person.gender == "Madame" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "ou Monsieur_2" => @second_person.gender == "Monsieur" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "Née le_2" => @second_person.birthday.strftime('%d/%m/%Y'),
      "à_2" => @second_person.place_birth,
      "Inscrite au tableau du Conseil départemental de lordre de" => @second_person.registered_ordre,
      "sous le numéro_2" => @second_person.n_ordinal,
      "Demeurant" => @second_person.address_pro,
      "Adresse électronique_2" => @contrat.status == "perso_2" ? current_user.email : @contrat.email,
      "Madame_3" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "ou Monsieur_3" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "Madame_4" => @second_person.gender == "Madame" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "masseurkinésithérapeute de lela remplacer pendant" => @second_person.gender == "Monsieur" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "Conformément à larticle R 4321107 alinéa 3 du code de la santé publique Madame" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "ou Monsieur_4" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "Madame_5" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "ou Monsieur_5" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "Madame_6" => @second_person.gender == "Madame" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "ou Monsieur_6" => @second_person.gender == "Monsieur" ? "#{@second_person.name} #{@second_person.first_name}" : "",
      "Madame_7" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "en" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
      "Le présent contrat prendra effet le" => @contrat.start_date.strftime('%d/%m/%Y'),
      "et se terminera le" => @contrat.end_date.strftime('%d/%m/%Y'),
      "Sur le total des honoraires perçus et facturés pendant le remplacement le remplacé en" => @contrat.retro,
      "versement" => "#{@contrat.payment_limit} de chaque mois",
      "Par conséquent le remplaçant sinterdit toute installation à titre libéral dans un rayon de" => "#{@contrat.rayon_install}km",
      "kinésithérapeutes de" => @contrat.conflict_order,
      "Fait le" => @contrat.made_on.strftime('%d/%m/%Y'),
      "A" => @contrat.to
    }
    pdf_path = "public/contrat_template/rempla_edit.pdf"
    filled_pdf_path = "public/contrat_template/remplacement.pdf"
    @pdf.fill_form(pdf_path, filled_pdf_path, data)
    send_file filled_pdf_path, type: 'application/pdf', disposition: 'attachment'
  end

def assistanat
  data = {
    "Madame" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
    "ou Monsieur" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
    "Née le" => @first_person.birthday.strftime('%d/%m/%Y'),
    "à" => @first_person.place_birth,
    "Inscrit e au tableau du Conseil départemental de lordre de" => @first_person.registered_ordre,
    "sous le numéro" => @first_person.n_ordinal,
    "Adresse professionnelle" => @first_person.address_pro,
    "Adresse électronique" => @contrat.status == "perso_1" ? current_user.email : @contrat.email,
    "Madame_2" => @second_person.gender == "Madame" ? "#{@second_person.name} #{@second_person.first_name}" : "",
    "ou Monsieur_2" => @second_person.gender == "Monsieur" ? "#{@second_person.name} #{@second_person.first_name}" : "",
    "Née le_2" => @second_person.birthday.strftime('%d/%m/%Y'),
    "à_2" => @second_person.place_birth,
    "Inscrite au tableau du Conseil départemental de lordre de" => @second_person.registered_ordre,
    "sous le numéro_2" => @second_person.n_ordinal,
    "Demeurant" => @second_person.address_pro,
    "Adresse électronique_2" => @contrat.status == "perso_2" ? current_user.email : @contrat.email,
    "MadameMonsieur" => "#{@first_person.name} #{@first_person.first_name}",
    "MadameMonsieur_2" => "#{@second_person.name} #{@second_person.first_name}",
    "dassistanat" => @first_person.address_pro,
    "undefined_4" => "#{@first_person.name} #{@first_person.first_name}",
    "Lassistant libéral MadameMonsieur" => "#{@second_person.name} #{@second_person.first_name}",
    "undefined_5" => "#{@first_person.name} #{@first_person.first_name}",
    "La présente convention entrera en vigueur le" => @contrat.start_date.strftime('%d/%m/%Y'),
    "pour une durée de" => "#{(@contrat.end_date.year * 12 + @contrat.end_date.month) - (@contrat.start_date.year * 12 + @contrat.start_date.month) + 1} mois",
    "undefined_6" => @contrat.n_urssaf,
    "undefined_7" => @contrat.retro,
    "de chaque mois11" => @contrat.payment_limit,
    "refus" => @contrat.nb_refus,
    "refus successifs du titulaire lassistant libéral pourra librement choisir son remplaçant Lassistant libéral" => @contrat.nb_refus,
    "En cas de cessation des relations contractuelles lassistant libéral sinterdira dexercer sa profession à" => @contrat.blackout_period,
    "sur un rayon de" => "#{@contrat.rayon_install}km",
    "départemental" => @contrat.conflict_order,
    "de" => @contrat.conflict_order,
    "Fait le" => @contrat.made_on.strftime('%d/%m/%Y'),
    "A" => @contrat.to
  }
  pdf_path = "public/contrat_template/assistanat.pdf"
  filled_pdf_path = "public/contrat_template/assistanat_edit.pdf"
  @pdf.fill_form(pdf_path, filled_pdf_path, data)
  send_file filled_pdf_path, type: 'application/pdf', disposition: 'attachment'
end

def collaboration
  data = {
  "Madame" => @first_person.gender == "Madame" ? "#{@first_person.name} #{@first_person.first_name}" : "",
  "ou Monsieur" => @first_person.gender == "Monsieur" ? "#{@first_person.name} #{@first_person.first_name}" : "",
  "Née le" => @first_person.birthday.strftime('%d/%m/%Y'),
  "Inscrit e au tableau du Conseil départemental de lordre de" => @first_person.registered_ordre,
  "sous le numéro" => @first_person.n_ordinal,
  "Adresse professionnelle" => @first_person.address_pro,
  "Adresse électronique" => @contrat.status == "perso_1" ? current_user.email : @contrat.email,
  "Madame_2" => @second_person.gender == "Madame" ? "#{@second_person.name} #{@second_person.first_name}" : "",
  "ou Monsieur_2" => @second_person.gender == "Monsieur" ? "#{@second_person.name} #{@second_person.first_name}" : "",
  "Née le_2" => @second_person.birthday.strftime('%d/%m/%Y'),
  "Inscrit e au tableau du Conseil départemental de lordre de_2" => @second_person.registered_ordre,
  "sous le numéro_2" => @second_person.n_ordinal,
  "Demeurant" => @second_person.address_pro,
  "Adresse électronique_2" => @contrat.status == "perso_2" ? current_user.email : @contrat.email,
  "de" => @first_person.address_pro,
  "La présente convention entrera en vigueur le" => @contrat.start_date.strftime('%d/%m/%Y'),

app/helpers/contrats_helper.rb
module ContratsHelper
end

app/views/contrats/_contrat.html.erb
<div id="<%= dom_id contrat %>">
  <p class="line">
    <strong>Type de contrat :</strong>
    <%= contrat.name_contrat.capitalize %>
  </p>

  <p class="line">
    <% if contrat.name_contrat == "remplacement" %>
      <strong><%= @first_person.gender == "Monsieur" ? "Le remplacé :" : "La remplacée :" %></strong>
    <% else %>
      <strong><%= @first_person.gender == "Monsieur" ? "Le titulaire :" : "La titulaire :" %></strong>
    <% end %>
    <%= "#{@first_person.gender} #{@first_person.name} #{@first_person.first_name}" %>
  </p>
  
  <p class="line">
    <% if contrat.name_contrat == "remplacement" %>
      <strong><%= @second_person.gender == "Monsieur" ? "Le remplaçant :" : "La remplaçante :" %></strong>
    <% elsif contrat.name_contrat == "assistanat" %>
      <strong><%= @second_person.gender == "Monsieur" ? "L'assistant :" : "L'assistante :" %></strong>
    <% else %>
      <strong><%= @second_person.gender == "Monsieur" ? "Le collaborateur :" : "La collaboratrice :" %></strong>
    <% end %>
    <%= "#{@second_person.gender} #{@second_person.name} #{@second_person.first_name}" %>
  </p>

  <p class="line">
    <strong>Commence le :</strong>
    <%= contrat.start_date&.strftime('%d/%m/%Y') %>
  </p>
  
  <p class="line">
    <% if contrat.name_contrat == "remplacement" %>
      <strong>Se termine le :</strong>
      <%= contrat.end_date&.strftime("%d/%m/%Y") %>
    <% else %>
      <strong>Pour une durée de :</strong>
      <%= "#{(contrat.end_date.year * 12 + contrat.end_date.month) - (contrat.start_date.year * 12 + contrat.start_date.month) + 1} mois" %>
    <% end %>
  </p>

  <p class="line">
    <strong>Rétrocéssion de :</strong>
    <%= "#{contrat.retro} %" %>
  </p>

  <p class="line">
    <strong>À verser avant le :</strong>
    <%= "#{contrat.payment_limit} de chaque mois" %>
  </p>

  <p class="line">
    <strong>Installation en libéral interdite dans un rayon de :</strong>
    <%= "#{contrat.rayon_install}km" %>
  </p>

  <p class="line">
    <strong>En cas de conflit contacter l'Ordre de :</strong>
    <%= contrat.conflict_order %>
  </p>  
  
  <p class="line">
    <strong>Fait le :</strong>
    <%= contrat.made_on&.strftime("%d/%m/%Y") %>
  </p>  
  
  <p class="line">
    <strong>À :</strong>
    <%= contrat.to %>
  </p>
</div>

app/views/contrats/_form.html.erb
<%= form_with(model: contrat) do |form| %>
  <% if contrat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contrat.errors.count, "error") %> prohibited this contrat from being saved:</h2>
      <ul>
        <% contrat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="center">
    <div class="column">
      <div data-controller="form-contrat">
        <div>
          <%= form.button "Valider", formaction: new_contrat_path, formmethod: :get, data: { turbo_frame: :urrsaf_field, form_contrat_target: "submitbtn" } %>
          <%= form.label :name_contrat, "Choix du contrat :" %>
          <%= form.select :name_contrat, Contrat.name_contrats, {include_blank: true}, data: { action: "change->form-contrat#remotesubmit" } %>
        </div>

        <div>
          <%= form.label :gender, "Genre :" %>
          <%= form.select :gender, ['Monsieur', 'Madame'] %>
        </div>
      </div>

      <div>
        <%= form.label :name, "Nom :" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :birthday, "Date de naissance :" %>
        <%= form.date_field :birthday, { prompt: true, start_year: Date.today.year - 80, end_year: Date.today.year - 18, order: [:day, :month, :year], class: "medium-width" } %>
      </div>

      <div>
        <%= form.label :registered_ordre, "Inscrit à l'Ordre de :" %>
        <%= departement_select(form, :registered_ordre) do %>
          <% if form.object.registered_ordre.present? %>
            <%= content_tag(:option, form.object.registered_ordre, value: form.object.registered_ordre, selected: true) %>
          <% end %>
        <% end %>
      </div>

      <div>
        <%= form.label :address_pro, "Adresse :" %>
        <%= form.text_field :address_pro %>
      </div>

      <div>
        <%= form.label :start_date, "Commence le :" %>
        <%= form.date_field :start_date, value: contrat.start_date.present? ? contrat.start_date : Date.current, class: "medium-width" %>
      </div>
            
      <div>
        <%= form.label :retro, "Rétrocession de :" %>
        <%= form.number_field :retro, class: "small-width" %>%
      </div>

      <div>
        <%= form.label :conflict_order, "En cas de conflit contacter l'Ordre de :" %>
        <%= departement_select(form, :conflict_order) %>
      </div>
    </div>

    <div class="column">
      <div class="radio_wrap">
        <%= form.radio_button :status, "perso_1", class: 'radio_label' %>
        <div id="status_1">Je me fais remplacer</div>
      </div>

      <div class="radio_wrap">
        <%= form.radio_button :status, "perso_2", class: 'radio_label' %>
        <div id="status_2">Je remplace</div>
      </div>

      <div>
        <%= form.label :first_name, "Prénom :" %>
        <%= form.text_field :first_name %>
      </div>

      <div>
        <%= form.label :place_birth, "Lieu de naissance :" %>
        <%= form.text_field :place_birth %>
      </div>

      <div>
        <%= form.label :n_ordinal, "Numéro ordinal :" %>
        <%= form.number_field :n_ordinal %>
      </div>

      <div>
        <%= form.label :email, "Email :" %>
        <%= form.email_field :email %>
      </div>

      <div>
        <%= form.label :end_date, "Se termine le :" %>
        <%= form.date_field :end_date, value: contrat.end_date.present? ? contrat.end_date : Date.current, class: "medium-width" %>
      </div>

      <div>
        <%= form.label :payment_limit, "À verser avant le :" %>
        <%= form.select :payment_limit, options_for_select([5, 15, 30]), prompt: '5/15/30' %> du mois
      </div>

      <div>
        <%= form.label :rayon_install, "Dans un rayon de " %>
        <%= form.number_field :rayon_install, class: "small-width" %> km autour du cabinet
      </div>
    </div>
  </div>

      <%= turbo_frame_tag :urrsaf_field do %>
        <% if contrat.assistanat? %>
          <%= turbo_stream.update "status_1", html: "Je suis le titulaire" %>
          <%= turbo_stream.update "status_2", html: "Je suis l'assistant" %>
          <div>
            <%= form.label :n_urssaf, "N° d'URSSAF de l'assistant :" %>
            <%= form.number_field :n_urssaf, value: contrat.n_urssaf %>
          </div>
          
          <div>
            <%= form.label :nb_refus, "Nb max de refus successifs du titulaire :" %>
            <%= form.number_field :nb_refus, value: contrat.nb_refus, class: "small-width" %>
          </div>

          <div>
            <%= form.label :blackout_period, "Installation en libéral interdite pendant une durée de :" %>
            <%= form.number_field :blackout_period, value: contrat.blackout_period, class: "small-width" %> mois
          </div>
        <% elsif contrat.collaboration? %>
          <%= turbo_stream.update "status_1", html: "Je suis le titulaire" %>
          <%= turbo_stream.update "status_2", html: "Je suis le collaborateur" %>      
          <div>
            <%= form.label :n_urssaf, "N° URSSAF du collaborateur :" %>
            <%= form.number_field :n_urssaf, value: contrat.n_urssaf %>
          </div>  

          <div>
            <%= form.label :nb_refus, "Nb max de refus successifs du titulaire :" %>
            <%= form.number_field :nb_refus, value: contrat.nb_refus, class: "small-width" %>
          </div>

          <div>
            <%= form.label :blackout_period, "Installation en libéral interdite pendant une durée de :" %>
            <%= form.number_field :blackout_period, value: contrat.blackout_period, class: "small-width" %> mois
          </div>
        <% end %>
      <% end %>

  <div class="center">
    <div class="column">
      <div>
        <%= form.label :made_on, "Fait le :" %>
        <%= form.date_field :made_on, value: Date.current, class: "medium-width" %>
      </div>
    </div>

    <div class="column">
      <div>
        <%= form.label :to, "À :" %>
        <%= form.text_field :to %>
      </div>
    </div>
  </div>

  <div class="center">
    <%= form.submit "Enregistrer", class: 'btn btn--primary' %>
  </div>
<% end %>

app/views/contrats/edit.html.erb
<div class="header">
    <h1>Modifier contrat</h1>
</div>

<div class="container">
  <div class="form">
    <%= render "form", contrat: @contrat %>

    <div class="option">
      <%= link_to "Retour", contrats_path, class: 'btn btn--light' %>
    </div>
  </div>
</div>

app/views/contrats/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="header">
  <h1>Mes contrats</h1>
  <% if current_user.information %>
    <%= link_to "Nouveau", new_contrat_path, class: 'btn btn--secondary' %>
  <% else %>
    <%= link_to "Nouveau", new_information_path %>
  <% end %>
</div>

<div id="contrats" class="container">
  <% @contrats.each do |contrat| %>
    <div class="form">
      <p class="line"><strong>Type de contrat :</strong> <%= contrat.name_contrat.capitalize %></p>
      <p class="line"><strong>Du </strong><%= "#{contrat.start_date&.strftime("%d %B")} au #{contrat.end_date&.strftime("%d %B %Y")}" %></p>
      <p class="line"><strong>Entre </strong><%= "#{contrat.information.name} #{contrat.information.first_name} et #{contrat.name} #{contrat.first_name}" %></p>
      <div class="option">
        <%= link_to "Voir contrat", contrat, class: 'btn btn--light' %>
        <%= button_to "Supprimer contrat", contrat, method: :delete, class: 'btn btn--light' %>
      </div>
    </div>
  <% end %>
</div>

app/views/contrats/new.html.erb
<%= turbo_frame_tag @contrat do %>
  <div class="header">
    <h1>Nouveau contrat</h1>
  </div>
  <div class="container">
    <div class="form">
      <%= render "form", contrat: @contrat %>

      <div class="option">
        <%= link_to "Retour", contrats_path, class: 'btn btn--light' %>
      </div>
    </div>
  </div>
<% end %>

app/views/contrats/show.html.erb
<p style="color: green"><%= notice %></p>
  
<div class="header">
  <h1>Votre contrat :</h1>
</div>

<div class="container">
  <div class="form">
    <%= render @contrat %>

    <div class="option">
      <% lien = send("#{@contrat.name_contrat.downcase}_contrat_path", @contrat) %>
      <%= link_to "Télécharger", lien, method: :get, class: 'btn btn--light' %> |
      <%= link_to "Modifier", edit_contrat_path(@contrat), class: 'btn btn--light' %> |
      <%= button_to "Supprimer ce contrat", @contrat, method: :delete, class: 'btn btn--light' %>
    </div>
  </div>
</div>